smashUltimateCharacterList = [
    "Mario",
    "Donkey Kong",
    "Link",
    "Samus",
    "Dark Samus",
    "Yoshi",
    "Kirby",
    "Fox",
    "Pikachu",
    "Luigi",
    "Ness",
    "Captain Falcon",
    "Jigglypuff",
    "Peach",
    "Daisy",
    "Bowser",
    "Ice Climbers",
    "Sheik",
    "Zelda",
    "Dr. Mario",
    "Pichu",
    "Falco",
    "Marth",
    "Lucina",
    "Young Link",
    "Ganondorf",
    "Mewtwo",
    "Roy",
    "Chrom",
    "Mr. Game & Watch",
    "Meta Knight",
    "Pit",
    "Dark Pit",
    "Zero Suit Samus",
    "Wario",
    "Snake",
    "Ike",
    "Pokemon Trainer",
    "Diddy Kong",
    "Lucas",
    "Sonic",
    "King Dedede",
    "Olimar",
    "Lucario",
    "ROB",
    "Toon Link",
    "Wolf",
    "Villager",
    "Mega Man",
    "Wii Fit Trainer",
    "Rosalina & Luma",
    "Little Mac",
    "Greninja",
    "Mii Brawler",
    "Mii Swordfighter",
    "Mii Gunner",
    "Palutena",
    "Pac-Man",
    "Robin",
    "Shulk",
    "Bowser Jr.",
    "Duck Hunt",
    "Ryu",
    "Ken",
    "Cloud",
    "Corrin",
    "Bayonetta",
    "Inkling",
    "Ridley",
    "Simon",
    "Richter",
    "King K. Rool",
    "Isabelle",
    "Incineroar",
    "Piranha Plant",
    "Joker",
    "Hero",
    "Banjo & Kazooie",
    "Terry",
    "Byleth",
    "Min Min",
    "Steve",
    "Sephiroth",
    "Aegis",
    "Kazuya",
    "Sora"
]

smashUltimateCharacterListAliases = {
    "dk": "Donkey Kong",
    "pika": "Pikachu",
    "puff": "Jigglypuff",
    "icies": "Ice Climbers",
    "doc": "Dr. Mario",
    "yink": "Young Link",
    "ganon": "Ganondorf",
    "m2": "Mewtwo",
    "gnw": "Mr. Game & Watch",
    "mk": "Meta Knight",
    "zss": "Zero Suit Samus",
    "pt": "Pokemon Trainer",
    "diddy": "Diddy Kong",
    "ddd": "King Dedede",
    "tink": "Toon Link",
    "villy": "Villager",
    "wft": "Wii Fit Trainer",
    "rosa": "Rosalina & Luma",
    "rosalina": "Rosalina & Luma",
    "mac": "Little Mac",
    "gren": "Greninja",
    "brawler": "Mii Brawler",
    "swordfighter": "Mii Swordfighter",
    "gunner": "Mii Gunner",
    "palu": "Palutena",
    "pac": "Pac-Man",
    "pacman": "Pac-Man",
    "dh": "Duck Hunt",
    "corn": "Corrin",
    "the best character": "Robin",
    "bayo": "Bayonetta",
    "krool": "King K. Rool",
    "kkr": "King K. Rool",
    "isa": "Isabelle",
    "incin": "Incineroar",
    "plant": "Piranha Plant",
    "banjo": "Banjo & Kazooie",
    "minmin": "Min Min",
    "alex": "Steve",
    "enderman": "Steve",
    "sephi": "Sephiroth",
    "kazu": "Kazuya",
    "pyra": "Aegis",
    "mythra": "Aegis",
    "pythra": "Aegis",
    "clownboy": "Sora"
}

for character in smashUltimateCharacterList:
    smashUltimateCharacterListAliases[character.lower()] = character
